# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1280, 720)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.label.setStyleSheet("QFrame {\n"
"    background-color: #ECEFF1;\n"
"}\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame_prior = QtWidgets.QFrame(Dialog)
        self.frame_prior.setGeometry(QtCore.QRect(160, 110, 300, 300))
        self.frame_prior.setStyleSheet("QFrame {\n"
"    background-color: #B0BEC5;\n"
"}\n"
"")
        self.frame_prior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_prior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_prior.setObjectName("frame_prior")
        self.frame_current = QtWidgets.QFrame(Dialog)
        self.frame_current.setGeometry(QtCore.QRect(510, 110, 300, 300))
        self.frame_current.setStyleSheet("QFrame {\n"
"    background-color: #B0BEC5;\n"
"}\n"
"")
        self.frame_current.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_current.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_current.setObjectName("frame_current")
        self.frame_heatmap = QtWidgets.QFrame(Dialog)
        self.frame_heatmap.setGeometry(QtCore.QRect(850, 110, 300, 300))
        self.frame_heatmap.setStyleSheet("QFrame {\n"
"    background-color: #B0BEC5;\n"
"}\n"
"")
        self.frame_heatmap.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_heatmap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_heatmap.setObjectName("frame_heatmap")
        self.PriorImage = QtWidgets.QPushButton(Dialog)
        self.PriorImage.setGeometry(QtCore.QRect(160, 430, 301, 23))
        self.PriorImage.setStyleSheet("QPushButton {\n"
"    background-color: #E91E63;\n"
"    color: #FAFAFA;\n"
"    padding: 5px 10px;\n"
"    border-radius: 50px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EC407A;\n"
"}\n"
"")
        self.PriorImage.setObjectName("PriorImage")
        self.CurrentImage = QtWidgets.QPushButton(Dialog)
        self.CurrentImage.setGeometry(QtCore.QRect(510, 430, 301, 23))
        self.CurrentImage.setStyleSheet("QPushButton {\n"
"    background-color: #E91E63;\n"
"    color: #FAFAFA;\n"
"    padding: 5px 10px;\n"
"    border-radius: 50px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EC407A;\n"
"}\n"
"")
        self.CurrentImage.setObjectName("CurrentImage")
        self.GenerateHeatmap = QtWidgets.QPushButton(Dialog)
        self.GenerateHeatmap.setGeometry(QtCore.QRect(850, 430, 301, 23))
        self.GenerateHeatmap.setStyleSheet("QPushButton {\n"
"    background-color: #E91E63;\n"
"    color: #FAFAFA;\n"
"    padding: 5px 10px;\n"
"    border-radius: 50px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EC407A;\n"
"}\n"
"")
        self.GenerateHeatmap.setObjectName("GenerateHeatmap")
        self.RemoveArtifactsPrior = QtWidgets.QPushButton(Dialog)
        self.RemoveArtifactsPrior.setGeometry(QtCore.QRect(160, 470, 301, 23))
        self.RemoveArtifactsPrior.setStyleSheet("QPushButton {\n"
"    background-color: #E91E63;\n"
"    color: #FAFAFA;\n"
"    padding: 5px 10px;\n"
"    border-radius: 50px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EC407A;\n"
"}\n"
"")
        self.RemoveArtifactsPrior.setObjectName("RemoveArtifactsPrior")
        self.RemoveArtifactsCurrent = QtWidgets.QPushButton(Dialog)
        self.RemoveArtifactsCurrent.setGeometry(QtCore.QRect(510, 470, 301, 23))
        self.RemoveArtifactsCurrent.setStyleSheet("QPushButton {\n"
"    background-color: #E91E63;\n"
"    color: #FAFAFA;\n"
"    padding: 5px 10px;\n"
"    border-radius: 50px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EC407A;\n"
"}\n"
"")
        self.RemoveArtifactsCurrent.setObjectName("RemoveArtifactsCurrent")
        self.RunTheModel = QtWidgets.QPushButton(Dialog)
        self.RunTheModel.setGeometry(QtCore.QRect(850, 470, 301, 23))
        self.RunTheModel.setStyleSheet("QPushButton {\n"
"    background-color: #E91E63;\n"
"    color: #FAFAFA;\n"
"    padding: 5px 10px;\n"
"    border-radius: 50px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EC407A;\n"
"}\n"
"")
        self.RunTheModel.setObjectName("RunTheModel")
        self.ResultSection = QtWidgets.QLabel(Dialog)
        self.ResultSection.setGeometry(QtCore.QRect(340, 560, 661, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ResultSection.setFont(font)
        self.ResultSection.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ResultSection.setAlignment(QtCore.Qt.AlignCenter)
        self.ResultSection.setObjectName("ResultSection")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.PriorImage.setText(_translate("Dialog", "Uploade Prior Image"))
        self.CurrentImage.setText(_translate("Dialog", "Upload Current Image"))
        self.GenerateHeatmap.setText(_translate("Dialog", "Generate Heatmap"))
        self.RemoveArtifactsPrior.setText(_translate("Dialog", "Remove Artifacts"))
        self.RemoveArtifactsCurrent.setText(_translate("Dialog", "Remove Artifacts"))
        self.RunTheModel.setText(_translate("Dialog", "Run the Model"))
        self.ResultSection.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
